---
version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: echo 'export MY_ENV_VAR="FOO"' >> "$BASH_ENV"
      - run:
          name: What branch am I on?
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: What branch am I on now?
          command: echo $CIRCLE_BRANCH
      - run:
          name: What was my custom environment variable?
          command: echo ${DOCKERHUB_USERNAME}
      - run:
          name: Print an env var stored in the Project
          command: echo ${PROJECT_ENV_VAR}
      - run:
          name: Print an env var stored in a Context
          command: echo ${DOCKERHUB_PASSWORD}
workflows:
  build:
    jobs:
      - build:
          context: Testing-Env-Vars
