orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: akshayasharma770/node-test-aks
    docker:
      - image: circleci/node:latest

jobs:
    buildNodejs:
      executor: docker-publisher
      steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm i
    publishLatestToHub: 
      executor: docker-publisher
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              docker logout
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin --help
              docker build -t node-test-aks .
              docker push node-test-aks:latest
workflows:
  version: 2
  build-master:
    jobs:
       - buildNodejs
       - publishLatestToHub
