orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: akshayasharma770/node-test-aks
    docker:
      - image: circleci/node:latest

jobs:
    buildNodejs:
      executor: docker-publisher
      steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm i
    publishLatestToHub: 
      executor: docker-publisher
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              sudo docker logout
              echo "$DOCKERHUB_PASSWORD" | sudo docker login -u "$DOCKERHUB_USERNAME" --password-stdin --help
              sudo docker build -t mylocalimage .
              sudo docker tag mylocalimage:latest akshayasharma770/testing:myfirstimagepush
              sudo docker push akshayasharma770/testing:myfirstimagepush
workflows:
  version: 2
  build-master:
    jobs:
       - buildNodejs
       - publishLatestToHub
