version: 2
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1
      - image: alpine:latest
    steps:
      - checkout
      - run: node --version
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build application Docker image
          command: |
            docker build -t node-test-aks .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo ${{ env.$DOCKER_TOKEN}} | docker login -u ${{ env.$DOCKERHUB_USERNAME}} --password-stdin
            docker push node-test-aks:latest

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context:
            - cred
