orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: akshayasharma770/node-test-aks
    docker:
      - image: circleci/node:latest

jobs:
    buildNodejs:
      executor: docker-publisher
      steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm i
    publishLatestToHub: 
      executor: docker-publisher
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker build -t mylocalimage -f Dockerfile .
              docker tag mylocalimage $IMAGE_NAME:latest
              docker images
              docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
       - buildNodejs
       - publishLatestToHub
